includes:
  - env_variables.yaml

runtime: nodejs20
env: standard

instance_class: F1

automatic_scaling:
  target_cpu_utilization: 0.65
  min_instances: 0
  max_instances: 2

env_variables:
  NODE_ENV: "production"

entrypoint: node dist/index.js
